version: "3.3"

services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./data/clickhouse:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: crypto
      CLICKHOUSE_USER: crypto
      CLICKHOUSE_PASSWORD: crypto
