{{ with $.Values.publisher }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-trade.fullnamePublisher" $ }}
  labels:
    {{ include "crypto-trade.labels" $ | nindent 4 }}
data:
  ENV: {{ .env }}
  PUBLISH_INTERVAL_MS: {{ .publishIntervalMs | quote }}
  NUM_PUBLISHERS: {{ .numPublishers | quote }}
  SUBJECT: {{ .subject }}
{{ end }}