{{ with $.Values.publisher }}
{{ $fullName := include "crypto-trade.fullnamePublisher" $ }}
{{ $selectorLabels := include "crypto-trade.selectorLabelsPublisher" $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName  }}
  labels:
    {{ include "crypto-trade.labels" $ | nindent 4 }}
spec:
  {{ if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      {{ $selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ $selectorLabels | nindent 8  }}
    spec:
      containers:
        - name: {{ $fullName }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{ with .resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          envFrom:
            - configMapRef:
                name: {{ $fullName }}
          env:
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "crypto-trade.secret" $ }}
                  key: NATS_URL
      {{ with .nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end}}
{{ end }}