nameOverride: ""
fullnameOverride: ""

# secret with this variables: CLICKHOUSE_URL, NATS_URL, MIGRATIONS_URL
secretNameOverride: crypto-trade

api: 
  image:
    repository: mmontes11/crypto-trade-api
    pullPolicy: IfNotPresent
    tag: "v0.10.0"

  service:
    type: ClusterIP
    port: 80
  
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 15
    
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 3
    periodSeconds: 15

  ingressRoute:
    enabled: true
    host: crypto-trade.mmontes-dev.duckdns.org
    entryPoints:
      - websecure

  env: production

  resources: {}

  replicaCount: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  nodeSelector: {}

publisher:
  image:
    repository: mmontes11/crypto-trade-publisher
    pullPolicy: IfNotPresent
    tag: "v0.10.0"
  
  env: production

  subject: trades

  publishIntervalMs: 10000

  numPublishers: 2

  resources: {}

  replicaCount: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  nodeSelector: {}

subscriber:
  image:
    repository: mmontes11/crypto-trade-subscriber
    pullPolicy: IfNotPresent
    tag: "v0.10.0"

  env: production

  subject: trades

  numSubscribers: 2

  resources: {}

  replicaCount: 1

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50

  nodeSelector: {}

nats:
  nameOverride: crypto-trade-nats
  image: nats:2.1.9-alpine3.12
  pullPolicy: IfNotPresent

  cluster:
    enabled: true
    replicas: 3
    noAdvertise: false

  natsbox:
    enabled: false
    image: synadia/nats-box:0.4.0
    pullPolicy: IfNotPresent

  reloader:
    enabled: true
    image: connecteverything/nats-server-config-reloader:0.6.0
    pullPolicy: IfNotPresent

  exporter:
    enabled: true
    image: synadia/prometheus-nats-exporter:0.5.0
    pullPolicy: IfNotPresent
    serviceMonitor:
      enabled: true
      path: /metrics

clickhouse:
  timezone: "UTC"

  clickhouse:
    image: "yandex/clickhouse-server"
    imageVersion: "19.14"
    imagePullPolicy: "IfNotPresent"
    
    replicas: "1"

  tabix: 
    enabled: false

