apiVersion: v1
kind: ConfigMap
metadata:
  name: subscriber
  namespace: crypto-trade
  labels:
    app: subscriber
    tier: back
data:
  ENV: production
  NATS_URL: nats://nats:4222
  NUM_SUBSCRIBERS: "2"
  SUBJECT: "trades"
  CLICKHOUSE_URL: tcp://clickhouse:9000?username=crypto&password=crypto&database=default
