apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: crypto-trade
  labels:
    app: subscriber
    tier: back
spec:
  selector:
    matchLabels:
      app: subscriber
      tier: back
  template:
    metadata:
      labels:
        app: subscriber
        tier: back
    spec:
      containers:
        - name: subscriber
          image: mmontes11/crypto-trade-subscriber
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: subscriber
            - secretRef:
                name: subscriber
