apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  namespace: crypto-trade
  labels:
    app: publisher
    tier: back
spec:
  selector:
    matchLabels:
      app: publisher
      tier: back
  template:
    metadata:
      labels:
        app: publisher
        tier: back
    spec:
      containers:
        - name: publisher
          image: mmontes11/crypto-trade-publisher
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: publisher
