{{ with $.Values.api }}
{{ $fullName := include "crypto-trade.fullnameApi" $ }}
{{ $selectorLabels := include "crypto-trade.selectorLabelsApi" $ }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName  }}
  labels:
    {{ include "crypto-trade.labels" $ | nindent 4 }}
spec:
  {{ if not .autoscaling.enabled }}
  replicas: {{ .replicaCount }}
  {{ end }}
  selector:
    matchLabels:
      {{ $selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ $selectorLabels | nindent 8  }}
    spec:
      containers:
        - name: {{ $fullName }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .service.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            {{ with .livenessProbe}}
              {{ toYaml . | nindent 12  }}
            {{ end }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            {{ with .readinessProbe }}
              {{ toYaml . | nindent 12  }}
            {{ end }}
          {{ with .resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{ end }}
          envFrom:
            - configMapRef:
                name: {{ $fullName }}
          env:
            - name: CLICKHOUSE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "crypto-trade.secret" $ }}
                  key: CLICKHOUSE_URL
      {{ with .nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{ end}}
{{ end }}