{{ with $.Values.api }}
{{ if .ingressRoute.enabled }}
{{ $fullName := include "crypto-trade.fullnameApi" $ }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{ include "crypto-trade.labels" $ | nindent 4 }}
spec:
  entryPoints:
    {{ range $entrypoint := .ingressRoute.entryPoints }}
    - {{ $entrypoint }}
    {{ end }}
  routes:
    - kind: Rule
      match: Host(`{{ .ingressRoute.host }}`)
      services:
        - kind: Service
          name: {{ $fullName }}
          port: {{ .service.port }}
{{ end }}
{{ end }}