{{ with $.Values.publisher }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-trade.fullnameSubscriber" $ }}
  labels:
    {{ include "crypto-trade.labels" $ | nindent 4 }}
data:
  ENV: {{ .env }}
  NUM_SUBSCRIBERS: {{ .publishIntervalMs }}
  SUBJECT: {{ .subject }}
{{ end }}