name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Publisher
        working-directory: ./cmd/publisher
        run: make build

      - name: Build Subscriber
        working-directory: ./cmd/subscriber
        run: make build

      - name: Build API
        working-directory: ./cmd/api
        run: make build

      - name: Bin Publisher
        uses: actions/upload-artifact@v2
        with:
          name: publisher
          path: ./cmd/publisher/bin/publisher

      - name: Bin Subscriber
        uses: actions/upload-artifact@v2
        with:
          name: subscriber
          path: ./cmd/subscriber/bin/subscriber

      - name: Bin API
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: ./cmd/api/bin/api
