name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test Crypto
        run: make cover

      - name: Cover Crypto
        uses: actions/upload-artifact@v2
        with:
          name: cover-crypto
          path: ./cover.html

      - name: Test API
        working-directory: ./cmd/api
        run: make cover

      - name: Cover API
        uses: actions/upload-artifact@v2
        with:
          name: cover-api
          path: ./cmd/api/cover.html
